# Generated by Claude Code -- 2026-02-13
# Panacea — Build automation

.PHONY: serve dev train experiment experiment-quick test-api docker-build docker-run clean

# --- Backend ---
serve:
	uvicorn app.main:app --host 0.0.0.0 --port 8000

dev:
	uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

# --- Training ---
train:
	python scripts/train_deep.py

train-quick:
	python scripts/train_deep.py --quick

# --- Experiments ---
experiment:
	python scripts/run_experiment.py

experiment-quick:
	python scripts/run_experiment.py --quick

# --- Testing ---
test-api:
	@echo "Testing /api/health ..."
	curl -s http://localhost:8000/api/health | python -m json.tool
	@echo "\nTesting /api/model-comparison ..."
	curl -s http://localhost:8000/api/model-comparison | python -m json.tool

# --- Docker ---
docker-build:
	docker build -t panacea .

docker-run:
	docker run -p 8000:8000 panacea

# --- Frontend ---
webapp-dev:
	cd webapp-react && npm run dev

webapp-build:
	cd webapp-react && npm run build

webapp-install:
	cd webapp-react && npm install

# --- Cleanup ---
clean:
	find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
	find . -name "*.pyc" -delete 2>/dev/null || true
