// Generated by Claude Code -- 2026-02-13
// Typed API client for Panacea backend

const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:8000';

// --- Response types ---

export interface HealthResponse {
  status: string;
  models_loaded: string[];
  device: string;
  n_models: number;
}

export interface TriageInfo {
  tier: 'LOW' | 'MODERATE' | 'HIGH';
  color: string;
  recommendation: string;
}

export interface ModelPrediction {
  risk_probability: number;
  miss_distance_km: number;
  triage: TriageInfo;
}

export interface PredictionResponse {
  baseline?: ModelPrediction;
  xgboost?: ModelPrediction;
  pitft?: ModelPrediction;
}

export interface ModelComparisonResult {
  model: string;
  auc_pr: number;
  auc_roc: number;
  f1: number;
  f1_at_50: number;
  n_positive: number;
  n_total: number;
  pos_rate: number;
  optimal_threshold: number;
  mae_log?: number;
  mae_km?: number;
}

export interface StalenessPoint {
  cutoff: number;
  auc_pr: number;
  f1: number;
  n_events?: number;
}

export interface StalenessResults {
  cutoffs: number[];
  baseline: StalenessPoint[];
  xgboost: StalenessPoint[];
  pitft: StalenessPoint[];
}

export interface ScreeningPair {
  name_1: string;
  name_2: string;
  norad_1: number;
  norad_2: number;
  risk_score: number;
  altitude_km: number;
  miss_estimate_km: number;
}

export interface ScreeningResponse {
  pairs: ScreeningPair[];
  n_candidates: number;
  n_total: number;
}

// --- API methods ---

async function fetchJson<T>(path: string, options?: RequestInit): Promise<T | null> {
  try {
    const resp = await fetch(`${API_BASE}${path}`, {
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    });
    if (!resp.ok) return null;
    return await resp.json();
  } catch {
    return null;
  }
}

export async function health(): Promise<HealthResponse | null> {
  return fetchJson<HealthResponse>('/api/health');
}

export async function getModelComparison(): Promise<ModelComparisonResult[] | null> {
  return fetchJson<ModelComparisonResult[]>('/api/model-comparison');
}

export async function getExperimentResults(): Promise<StalenessResults | null> {
  return fetchJson<StalenessResults>('/api/experiment-results');
}

export async function bulkScreen(
  tles: Record<string, unknown>[],
  topK = 10
): Promise<ScreeningResponse | null> {
  return fetchJson<ScreeningResponse>('/api/bulk-screen', {
    method: 'POST',
    body: JSON.stringify({ tles, top_k: topK }),
  });
}

export async function predictConjunction(
  cdmSequence: Record<string, unknown>[]
): Promise<PredictionResponse | null> {
  return fetchJson<PredictionResponse>('/api/predict-conjunction', {
    method: 'POST',
    body: JSON.stringify({ cdm_sequence: cdmSequence }),
  });
}
