// Generated by Claude Code -- 2026-02-13
// Typed API client for Panacea backend

const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:8000';

// --- Response types ---

export interface HealthResponse {
  status: string;
  models_loaded: string[];
  device: string;
  n_models: number;
}

export interface TriageInfo {
  tier: 'LOW' | 'MODERATE' | 'HIGH';
  color: string;
  recommendation: string;
}

export interface ModelPrediction {
  risk_probability: number;
  miss_distance_km: number;
  collision_probability?: number;
  collision_probability_log10?: number;
  triage: TriageInfo;
}

export interface PredictionResponse {
  baseline?: ModelPrediction;
  xgboost?: ModelPrediction;
  pitft?: ModelPrediction;
}

export interface ModelComparisonResult {
  model: string;
  auc_pr: number;
  auc_roc: number;
  f1: number;
  f1_at_50: number;
  n_positive: number;
  n_total: number;
  pos_rate: number;
  optimal_threshold: number;
  mae_log?: number;
  mae_km?: number;
}

export interface StalenessPoint {
  cutoff: number;
  auc_pr: number;
  f1: number;
  n_events?: number;
}

export interface StalenessResults {
  cutoffs: number[];
  baseline: StalenessPoint[];
  xgboost: StalenessPoint[];
  pitft: StalenessPoint[];
}

export interface TrajectoryPoint {
  h: number;     // hours from start
  d: number;     // separation distance km
  s1: number[];  // ECI [x, y, z] km
  s2: number[];  // ECI [x, y, z] km
}

export interface TrailPoint {
  h: number;     // hours from start
  d: number;     // separation distance km
  s1: number[];  // ECI [x, y, z] km
  s2: number[];  // ECI [x, y, z] km
}

export interface ScreeningPair {
  name_1: string;
  name_2: string;
  norad_1: number;
  norad_2: number;
  risk_score: number;
  altitude_km: number;
  miss_estimate_km: number;
  prediction_date?: string;
  tca_hours?: number;
  tca_min_distance_km?: number;
  /** Sparse trajectory (20-min steps, 5 days) for chart/slider */
  trajectory?: TrajectoryPoint[];
  /** Dense trail (1-min steps, ±30 min around TCA) for globe orbital paths */
  trail?: TrailPoint[];
  /** CDM fields — present when source is Space-Track CDM */
  source?: 'cdm' | 'tle_screening';
  pc?: number;
  miss_distance_km?: number;
  cdm_tca?: string;
  sat1_type?: string;
  sat2_type?: string;
  emergency_reportable?: string;
}

export interface ForecastModelMetrics {
  mode: string;
  n_pairs_total?: number;
  n_labeled?: number;
  n_positive?: number;
  positive_rate?: number;
  n_train?: number;
  n_test?: number;
  train?: { accuracy: number; precision: number; recall: number; f1: number; auc_pr: number };
  test?: { accuracy: number; precision: number; recall: number; f1: number; auc_pr: number };
}

export interface PipelineStats {
  generated_at: string;
  finetune_history: {
    date: string;
    pre_auc_pr: number;
    post_auc_pr: number;
    keep_new_model: boolean;
    n_outcomes: number;
    epochs_trained: number;
  }[];
  daily_history: {
    date: string;
    n_satellites_screened: number;
    n_candidate_pairs: number;
    n_predictions_logged: number;
    n_maneuvers?: number;
  }[];
  cdm_stats: {
    total_cdms: number;
    last_fetch: string;
    fetch_count: number;
    pc_high: number;
    pc_moderate: number;
    emergency_count: number;
  };
  forecast_model?: ForecastModelMetrics;
}

export interface ScreeningResponse {
  pairs: ScreeningPair[];
  n_candidates: number;
  n_total: number;
}

export interface StaticAlerts {
  generated_at: string;
  prediction_date: string;
  n_cdm_alerts?: number;
  n_tle_alerts?: number;
  pairs: ScreeningPair[];
}

// --- API methods ---

async function fetchJson<T>(path: string, options?: RequestInit): Promise<T | null> {
  try {
    const resp = await fetch(`${API_BASE}${path}`, {
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    });
    if (!resp.ok) return null;
    return await resp.json();
  } catch {
    return null;
  }
}

export async function health(): Promise<HealthResponse | null> {
  return fetchJson<HealthResponse>('/api/health');
}

export async function getModelComparison(): Promise<ModelComparisonResult[] | null> {
  return fetchJson<ModelComparisonResult[]>('/api/model-comparison');
}

export async function getExperimentResults(): Promise<StalenessResults | null> {
  return fetchJson<StalenessResults>('/api/experiment-results');
}

export async function bulkScreen(
  tles: Record<string, unknown>[],
  topK = 10
): Promise<ScreeningResponse | null> {
  return fetchJson<ScreeningResponse>('/api/bulk-screen', {
    method: 'POST',
    body: JSON.stringify({ tles, top_k: topK }),
  });
}

export async function predictConjunction(
  cdmSequence: Record<string, unknown>[]
): Promise<PredictionResponse | null> {
  return fetchJson<PredictionResponse>('/api/predict-conjunction', {
    method: 'POST',
    body: JSON.stringify({ cdm_sequence: cdmSequence }),
  });
}
