# Generated by Claude Code -- 2026-02-07
"""Download ESA Kelvins Collision Avoidance Challenge dataset from Zenodo."""

import os
import zipfile
import requests
from pathlib import Path
from tqdm import tqdm

ZENODO_URL = "https://zenodo.org/records/4463683/files"
# The dataset is a single zip file, not individual CSVs
FILES = [
    "Collision Avoidance Challenge - Dataset.zip",
]
DATA_DIR = Path(__file__).parent.parent / "data" / "cdm"


def download_file(url: str, dest: Path):
    """Download a file with progress bar."""
    resp = requests.get(url, stream=True)
    resp.raise_for_status()
    total = int(resp.headers.get("content-length", 0))
    with open(dest, "wb") as f, tqdm(total=total, unit="B", unit_scale=True, desc=dest.name) as pbar:
        for chunk in resp.iter_content(chunk_size=8192):
            f.write(chunk)
            pbar.update(len(chunk))


def main():
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    for filename in FILES:
        dest = DATA_DIR / filename
        if dest.exists():
            print(f"Already exists: {dest}")
        else:
            url = f"{ZENODO_URL}/{filename}"
            print(f"Downloading {url} ...")
            try:
                download_file(url, dest)
                print(f"Saved to {dest}")
            except Exception as e:
                print(f"Failed to download {filename}: {e}")
                print(f"Try manually: {url}")
                continue

        # Unzip if it's a zip file
        if dest.suffix == ".zip":
            print(f"Extracting {dest.name} ...")
            with zipfile.ZipFile(dest, "r") as zf:
                zf.extractall(DATA_DIR)
                print(f"Extracted {len(zf.namelist())} files:")
                for name in zf.namelist():
                    print(f"  {name}")


if __name__ == "__main__":
    main()
