# Generated by Claude Code -- 2026-02-08
"""Download all available CDMs from Space-Track cdm_public and save to CSV.

cdm_public only has a rolling ~30-day window of emergency-reportable CDMs.
As of Feb 2026, that's ~3,200 CDMs — all high-risk (100% have PC > 1e-5).
"""

import os
import requests
import csv
import json
from pathlib import Path

BASE = "https://www.space-track.org"
ROOT = Path(__file__).parent.parent
OUTPUT_DIR = ROOT / "data" / "cdm_spacetrack"


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Authenticate (credentials from environment variables)
    identity = os.environ.get("SPACETRACK_USER", "")
    password = os.environ.get("SPACETRACK_PASS", "")
    if not identity or not password:
        raise SystemExit("Set SPACETRACK_USER and SPACETRACK_PASS environment variables")

    s = requests.Session()
    s.post(f"{BASE}/ajaxauth/login", data={
        "identity": identity,
        "password": password,
    })
    print("Authenticated with Space-Track.org")

    # Download all available CDMs (currently ~3,200)
    print("\nDownloading all available CDMs from cdm_public ...")
    url = f"{BASE}/basicspacedata/query/class/cdm_public/orderby/CDM_ID asc/limit/100000/format/json"
    resp = s.get(url, timeout=180)

    if resp.status_code != 200:
        print(f"Failed: HTTP {resp.status_code}")
        return

    data = resp.json()
    print(f"Downloaded {len(data)} CDMs")

    if not data:
        print("No data available.")
        return

    # Save as CSV
    output_file = OUTPUT_DIR / "cdm_spacetrack_emergency.csv"
    fieldnames = list(data[0].keys())
    with open(output_file, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(data)

    print(f"Saved to {output_file}")

    # Stats
    pcs = [float(d["PC"]) for d in data if d.get("PC") is not None]
    null_pcs = sum(1 for d in data if d.get("PC") is None)
    pairs = set()
    for d in data:
        pair = tuple(sorted([str(d.get("SAT_1_ID", "")), str(d.get("SAT_2_ID", ""))]))
        pairs.add(pair)

    print(f"\nStats:")
    print(f"  Total CDMs:        {len(data)}")
    print(f"  With PC values:    {len(pcs)} ({null_pcs} null)")
    print(f"  Unique conjunctions: {len(pairs)}")
    if pcs:
        print(f"  PC range:          {min(pcs):.2e} to {max(pcs):.2e}")
        high_risk = sum(1 for p in pcs if p > 1e-5)
        print(f"  High risk:         {high_risk} ({100*high_risk/len(pcs):.0f}%)")
    print(f"  File size:         {output_file.stat().st_size / 1e6:.2f} MB")


if __name__ == "__main__":
    main()
