# Generated by Claude Code -- 2026-02-07
"""Download ESA Kelvins Collision Avoidance Challenge dataset from Zenodo."""

import zipfile
import subprocess
import sys
from pathlib import Path

# Direct Zenodo download URL (URL-encoded filename)
ZENODO_URL = "https://zenodo.org/records/4463683/files/Collision%20Avoidance%20Challenge%20-%20Dataset.zip"
ZIP_NAME = "Collision Avoidance Challenge - Dataset.zip"
DATA_DIR = Path(__file__).parent.parent / "data" / "cdm"


def main():
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    dest = DATA_DIR / ZIP_NAME

    if dest.exists():
        print(f"Already exists: {dest}")
    else:
        print(f"Downloading CDM dataset from Zenodo (~221MB) ...")
        print(f"URL: {ZENODO_URL}")
        # Use curl with resume support for reliability on large files
        result = subprocess.run(
            ["curl", "-L", "-C", "-", "-o", str(dest), ZENODO_URL],
            check=False,
        )
        if result.returncode != 0:
            print(f"curl failed (exit {result.returncode}). Try manually:")
            print(f"  curl -L -o \"{dest}\" \"{ZENODO_URL}\"")
            sys.exit(1)
        print(f"Saved to {dest} ({dest.stat().st_size / 1e6:.1f} MB)")

    # Extract
    print(f"Extracting {dest.name} ...")
    with zipfile.ZipFile(dest, "r") as zf:
        zf.extractall(DATA_DIR)
        print(f"Extracted {len(zf.namelist())} files:")
        for name in zf.namelist():
            size_mb = zf.getinfo(name).file_size / 1e6
            print(f"  {name} ({size_mb:.1f} MB)")


if __name__ == "__main__":
    main()
