# Generated by Claude Code -- 2026-02-07
"""Fetch live TLE data from CelesTrak API."""

import json
import requests
from pathlib import Path
from datetime import datetime

BASE_URL = "https://celestrak.org/NORAD/elements/gp.php"
DATA_DIR = Path(__file__).parent.parent / "data" / "tle"

GROUPS = {
    "active": "All active satellites",
    "stations": "Space stations (ISS, Tiangong, etc.)",
    "cosmos-2251-debris": "Cosmos 2251 collision debris (2009)",
    "iridium-33-debris": "Iridium 33 collision debris (2009)",
    "fengyun-1c-debris": "Fengyun 1C ASAT test debris (2007)",
    "cosmos-1408-debris": "Cosmos 1408 ASAT test debris (2021)",
    "starlink": "SpaceX Starlink constellation",
    "oneweb": "OneWeb constellation",
}


def fetch_group(group_name: str) -> list:
    """Fetch TLE data for a CelesTrak group in JSON format."""
    url = f"{BASE_URL}?GROUP={group_name}&FORMAT=json"
    print(f"Fetching {group_name} from {url} ...")
    resp = requests.get(url, timeout=30)
    resp.raise_for_status()
    data = resp.json()
    print(f"  Got {len(data)} objects")
    return data


def main():
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")

    all_objects = {}
    for group_name, description in GROUPS.items():
        try:
            data = fetch_group(group_name)
            outfile = DATA_DIR / f"{group_name}.json"
            with open(outfile, "w") as f:
                json.dump(data, f, indent=2)
            all_objects[group_name] = len(data)
        except Exception as e:
            print(f"  ERROR: {e}")

    # Save a summary
    summary = {
        "fetched_at": timestamp,
        "groups": all_objects,
        "total_objects": sum(all_objects.values()),
    }
    with open(DATA_DIR / "fetch_summary.json", "w") as f:
        json.dump(summary, f, indent=2)

    print(f"\nTotal objects fetched: {summary['total_objects']}")
    print(f"Saved to {DATA_DIR}")


if __name__ == "__main__":
    main()
