// Generated by Claude Code -- 2026-02-13
import type { ModelPrediction } from '../lib/api';

interface ModelComparisonProps {
  predictions: {
    baseline?: ModelPrediction;
    xgboost?: ModelPrediction;
    pitft?: ModelPrediction;
  };
}

const MODEL_META: Record<string, { label: string; color: string }> = {
  baseline: { label: 'Baseline', color: '#888888' },
  xgboost: { label: 'XGBoost', color: '#4fff8a' },
  pitft: { label: 'PI-TFT', color: '#4f8aff' },
};

export function ModelComparison({ predictions }: ModelComparisonProps) {
  const entries = Object.entries(predictions).filter(
    (entry): entry is [string, ModelPrediction] => entry[1] != null
  );

  if (entries.length === 0) return null;

  return (
    <div className="space-y-2">
      <div className="text-xs font-medium text-[var(--color-text-muted)] mb-1">
        Model Predictions
      </div>
      {entries.map(([key, pred]) => {
        const meta = MODEL_META[key] || { label: key, color: '#fff' };
        return (
          <div
            key={key}
            className="rounded-lg bg-[var(--color-surface-2)] p-2.5 text-xs"
          >
            <div className="flex items-center gap-2 mb-1.5">
              <div
                className="w-2 h-2 rounded-full"
                style={{ background: meta.color }}
              />
              <span className="font-medium">{meta.label}</span>
              <span
                className="ml-auto px-1.5 py-0.5 rounded text-[10px] font-bold"
                style={{
                  background: pred.triage.color + '22',
                  color: pred.triage.color,
                }}
              >
                {pred.triage.tier}
              </span>
            </div>
            <div className="flex justify-between text-[var(--color-text-muted)]">
              <span>Risk: {(pred.risk_probability * 100).toFixed(1)}%</span>
              <span>Miss: {pred.miss_distance_km.toFixed(1)} km</span>
            </div>
          </div>
        );
      })}
    </div>
  );
}
