// Generated by Claude Code -- 2026-02-13
import * as Tabs from '@radix-ui/react-tabs';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend,
  LineChart, Line, ResponsiveContainer,
} from 'recharts';
import type { ModelComparisonResult, StalenessResults } from '../lib/api';
import type { SatellitePosition } from '../lib/types';

interface RiskDashboardProps {
  modelComparison: ModelComparisonResult[] | null;
  experimentResults: StalenessResults | null;
  satellites: SatellitePosition[];
  visible: boolean;
  onClose: () => void;
}

const MODEL_COLORS: Record<string, string> = {
  'Orbital Shell Baseline': '#888888',
  'XGBoost (Engineered Features)': '#4fff8a',
  'PI-TFT (Physics-Informed Temporal Fusion Transformer)': '#4f8aff',
};

function shortModelName(name: string): string {
  if (name.includes('Baseline')) return 'Baseline';
  if (name.includes('XGBoost')) return 'XGBoost';
  if (name.includes('PI-TFT') || name.includes('Temporal')) return 'PI-TFT';
  return name;
}

function ModelsTab({ data }: { data: ModelComparisonResult[] }) {
  const chartData = data.map(m => ({
    name: shortModelName(m.model),
    'AUC-PR': parseFloat(m.auc_pr.toFixed(3)),
    'F1 (optimal)': parseFloat(m.f1.toFixed(3)),
    'AUC-ROC': parseFloat(m.auc_roc.toFixed(3)),
  }));

  return (
    <div className="p-3">
      <ResponsiveContainer width="100%" height={220}>
        <BarChart data={chartData} margin={{ top: 5, right: 20, left: 0, bottom: 5 }}>
          <CartesianGrid strokeDasharray="3 3" stroke="#333" />
          <XAxis dataKey="name" tick={{ fill: '#aaa', fontSize: 11 }} />
          <YAxis domain={[0, 1]} tick={{ fill: '#aaa', fontSize: 11 }} />
          <Tooltip
            contentStyle={{ background: '#1a1a2e', border: '1px solid #333', borderRadius: 8 }}
            labelStyle={{ color: '#fff' }}
          />
          <Legend wrapperStyle={{ fontSize: 11 }} />
          <Bar dataKey="AUC-PR" fill="#4fff8a" radius={[4, 4, 0, 0]} />
          <Bar dataKey="F1 (optimal)" fill="#4f8aff" radius={[4, 4, 0, 0]} />
          <Bar dataKey="AUC-ROC" fill="#8b5cf6" radius={[4, 4, 0, 0]} />
        </BarChart>
      </ResponsiveContainer>

      {/* Metric cards */}
      <div className="grid grid-cols-3 gap-2 mt-3">
        {data.map(m => (
          <div key={m.model} className="rounded-lg bg-[var(--color-surface-2)] p-2 text-center">
            <div className="text-[10px] text-[var(--color-text-muted)] mb-1">
              {shortModelName(m.model)}
            </div>
            <div className="text-lg font-bold" style={{ color: MODEL_COLORS[m.model] || '#fff' }}>
              {(m.auc_pr * 100).toFixed(1)}%
            </div>
            <div className="text-[10px] text-[var(--color-text-muted)]">AUC-PR</div>
          </div>
        ))}
      </div>
    </div>
  );
}

function ExperimentsTab({ data }: { data: StalenessResults }) {
  const chartData = data.cutoffs.map((cutoff, i) => ({
    cutoff: `${cutoff}d`,
    Baseline: parseFloat((data.baseline[i]?.auc_pr ?? 0).toFixed(3)),
    XGBoost: parseFloat((data.xgboost[i]?.auc_pr ?? 0).toFixed(3)),
    'PI-TFT': parseFloat((data.pitft[i]?.auc_pr ?? 0).toFixed(3)),
  }));

  return (
    <div className="p-3">
      <div className="text-xs text-[var(--color-text-muted)] mb-2">
        AUC-PR vs Data Staleness (time-to-TCA cutoff)
      </div>
      <ResponsiveContainer width="100%" height={220}>
        <LineChart data={chartData} margin={{ top: 5, right: 20, left: 0, bottom: 5 }}>
          <CartesianGrid strokeDasharray="3 3" stroke="#333" />
          <XAxis dataKey="cutoff" tick={{ fill: '#aaa', fontSize: 11 }} />
          <YAxis domain={[0, 1]} tick={{ fill: '#aaa', fontSize: 11 }} />
          <Tooltip
            contentStyle={{ background: '#1a1a2e', border: '1px solid #333', borderRadius: 8 }}
            labelStyle={{ color: '#fff' }}
          />
          <Legend wrapperStyle={{ fontSize: 11 }} />
          <Line type="monotone" dataKey="Baseline" stroke="#888888" strokeWidth={2} dot={{ r: 3 }} />
          <Line type="monotone" dataKey="XGBoost" stroke="#4fff8a" strokeWidth={2} dot={{ r: 3 }} />
          <Line type="monotone" dataKey="PI-TFT" stroke="#4f8aff" strokeWidth={2} dot={{ r: 3 }} />
        </LineChart>
      </ResponsiveContainer>
    </div>
  );
}

function DensityTab({ satellites }: { satellites: SatellitePosition[] }) {
  // Compute altitude histogram
  const BIN_WIDTH = 50; // km
  const bins: Record<number, number> = {};
  for (const sat of satellites) {
    const bin = Math.round(sat.alt / BIN_WIDTH) * BIN_WIDTH;
    if (bin >= 0 && bin <= 2000) {
      bins[bin] = (bins[bin] || 0) + 1;
    }
  }

  const chartData = Object.entries(bins)
    .map(([alt, count]) => ({ altitude: `${alt}`, count }))
    .sort((a, b) => parseInt(a.altitude) - parseInt(b.altitude));

  return (
    <div className="p-3">
      <div className="text-xs text-[var(--color-text-muted)] mb-2">
        Object density by altitude ({BIN_WIDTH}km bins, LEO only)
      </div>
      <ResponsiveContainer width="100%" height={220}>
        <BarChart data={chartData} margin={{ top: 5, right: 20, left: 0, bottom: 5 }}>
          <CartesianGrid strokeDasharray="3 3" stroke="#333" />
          <XAxis
            dataKey="altitude"
            tick={{ fill: '#aaa', fontSize: 9 }}
            interval={3}
            label={{ value: 'Altitude (km)', position: 'insideBottom', offset: -2, fill: '#666', fontSize: 10 }}
          />
          <YAxis tick={{ fill: '#aaa', fontSize: 11 }} />
          <Tooltip
            contentStyle={{ background: '#1a1a2e', border: '1px solid #333', borderRadius: 8 }}
            labelFormatter={(val) => `${val} km`}
          />
          <Bar dataKey="count" fill="#8b5cf6" radius={[2, 2, 0, 0]} />
        </BarChart>
      </ResponsiveContainer>
    </div>
  );
}

export function RiskDashboard({
  modelComparison,
  experimentResults,
  satellites,
  visible,
  onClose,
}: RiskDashboardProps) {
  if (!visible) return null;

  return (
    <div className="absolute bottom-12 left-4 right-4 max-h-[45vh] rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)]/95 backdrop-blur-md shadow-2xl z-20 flex flex-col">
      <div className="flex items-center justify-between px-4 py-2 border-b border-[var(--color-border)]">
        <h3 className="font-semibold text-sm">Risk Dashboard</h3>
        <button
          onClick={onClose}
          className="text-[var(--color-text-muted)] hover:text-[var(--color-text)] transition-colors text-lg leading-none"
        >
          x
        </button>
      </div>

      <Tabs.Root defaultValue="models" className="flex-1 overflow-hidden flex flex-col">
        <Tabs.List className="flex border-b border-[var(--color-border)] px-4">
          {['models', 'experiments', 'density'].map(tab => (
            <Tabs.Trigger
              key={tab}
              value={tab}
              className="px-3 py-2 text-xs font-medium text-[var(--color-text-muted)] border-b-2 border-transparent data-[state=active]:text-[var(--color-text)] data-[state=active]:border-[var(--color-accent)] transition-colors capitalize"
            >
              {tab}
            </Tabs.Trigger>
          ))}
        </Tabs.List>

        <div className="flex-1 overflow-y-auto">
          <Tabs.Content value="models">
            {modelComparison ? (
              <ModelsTab data={modelComparison} />
            ) : (
              <div className="p-4 text-xs text-[var(--color-text-muted)] text-center">
                No model comparison data available. Start the backend server.
              </div>
            )}
          </Tabs.Content>

          <Tabs.Content value="experiments">
            {experimentResults ? (
              <ExperimentsTab data={experimentResults} />
            ) : (
              <div className="p-4 text-xs text-[var(--color-text-muted)] text-center">
                No experiment data. Run: python scripts/run_experiment.py
              </div>
            )}
          </Tabs.Content>

          <Tabs.Content value="density">
            <DensityTab satellites={satellites} />
          </Tabs.Content>
        </div>
      </Tabs.Root>
    </div>
  );
}
