// Generated by Claude Code -- 2026-02-13
import { useState, useMemo, useCallback } from 'react';
import type { SatellitePosition, ObjectType } from '../lib/types';

interface SearchFilterProps {
  satellites: SatellitePosition[];
  onSelectSatellite: (sat: SatellitePosition) => void;
}

const TYPE_OPTIONS: { value: ObjectType | 'all'; label: string }[] = [
  { value: 'all', label: 'All Types' },
  { value: 'active', label: 'Active' },
  { value: 'debris', label: 'Debris' },
  { value: 'station', label: 'Stations' },
  { value: 'constellation', label: 'Constellation' },
  { value: 'rocket_body', label: 'Rocket Body' },
];

export function SearchFilter({ satellites, onSelectSatellite }: SearchFilterProps) {
  const [query, setQuery] = useState('');
  const [typeFilter, setTypeFilter] = useState<ObjectType | 'all'>('all');
  const [showResults, setShowResults] = useState(false);

  const results = useMemo(() => {
    if (!query && typeFilter === 'all') return [];

    const q = query.toLowerCase();
    return satellites
      .filter(sat => {
        if (typeFilter !== 'all' && sat.type !== typeFilter) return false;
        if (q) {
          return (
            sat.name.toLowerCase().includes(q) ||
            String(sat.noradId).includes(q) ||
            sat.objectId.toLowerCase().includes(q)
          );
        }
        return true;
      })
      .slice(0, 20);
  }, [satellites, query, typeFilter]);

  const handleSelect = useCallback(
    (sat: SatellitePosition) => {
      onSelectSatellite(sat);
      setShowResults(false);
      setQuery('');
    },
    [onSelectSatellite]
  );

  return (
    <div className="absolute top-4 left-1/2 -translate-x-1/2 z-30 w-full max-w-md px-4">
      <div className="flex items-center gap-2 rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)]/95 backdrop-blur-md px-3 py-2 shadow-lg">
        <svg
          className="w-4 h-4 text-[var(--color-text-muted)] shrink-0"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
          />
        </svg>
        <input
          type="text"
          value={query}
          onChange={e => {
            setQuery(e.target.value);
            setShowResults(true);
          }}
          onFocus={() => setShowResults(true)}
          placeholder="Search by name or NORAD ID..."
          className="flex-1 bg-transparent text-sm outline-none placeholder-[var(--color-text-muted)]"
        />
        <select
          value={typeFilter}
          onChange={e => {
            setTypeFilter(e.target.value as ObjectType | 'all');
            setShowResults(true);
          }}
          className="bg-transparent text-xs text-[var(--color-text-muted)] border-l border-[var(--color-border)] pl-2 outline-none cursor-pointer"
        >
          {TYPE_OPTIONS.map(opt => (
            <option key={opt.value} value={opt.value}>
              {opt.label}
            </option>
          ))}
        </select>
      </div>

      {showResults && results.length > 0 && (
        <div className="mt-1 rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)]/95 backdrop-blur-md shadow-lg max-h-60 overflow-y-auto">
          {results.map(sat => (
            <button
              key={sat.noradId}
              onClick={() => handleSelect(sat)}
              className="w-full px-3 py-2 text-left text-xs hover:bg-[var(--color-surface-2)] transition-colors flex items-center justify-between"
            >
              <div>
                <span className="font-medium">{sat.name}</span>
                <span className="text-[var(--color-text-muted)] ml-2">
                  #{sat.noradId}
                </span>
              </div>
              <span className="text-[var(--color-text-muted)]">
                {sat.alt.toFixed(0)} km
              </span>
            </button>
          ))}
        </div>
      )}

      {showResults && query && results.length === 0 && (
        <div className="mt-1 rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)]/95 backdrop-blur-md shadow-lg px-3 py-2 text-xs text-[var(--color-text-muted)] text-center">
          No objects found
        </div>
      )}
    </div>
  );
}
